[build]
command = "npm run build"
publish = "dist/public"
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[[redirects]]
from = "https://www.anoiak.com/*"
to = "https://anoiak.com/:splat"
status = 301
force = true
